
# Autogenerated using jinja files
from quixstreams import Application
from quixstreams.kafka import ConnectionConfig 
from beaver.pipeline import *
from dash import Dash
from dash.dependencies import Input, Output
from dash import dcc, html
import plotly.graph_objs as go
import threading
from plotly.subplots import make_subplots


from river import linear_model
from river import tree
from river import neighbors
from river import compose
from river import preprocessing
from river import metrics




linearReg = linear_model.LinearRegression(
    intercept_lr =0.1
)
hoeffTree = tree.HoeffdingAdaptiveTreeRegressor(
    grace_period =50,
    model_selector_decay =0.3,
    seed =0
)
knnReg = neighbors.KNNRegressor(
)
select = compose.SelectType((int,float)
)
selectstr = compose.SelectType(str
)
encoder = preprocessing.OneHotEncoder(
)
scaler = preprocessing.StandardScaler(
)
mae = metrics.MAE(
)
mse = metrics.MSE(
)
r2 = metrics.R2(
)



#Define connection
connectionConfig = ConnectionConfig(
    bootstrap_servers = 'localhost:39092',
    security_protocol = 'plaintext',
)

#Connection to Kafka
app = Application( 
    broker_address = connectionConfig,
    consumer_group = 'world-happiness',
    auto_offset_reset = 'earliest',
)

#Input topics 

input_topic_World_Happiness_Report = app.topic("World_Happiness_Report", value_deserializer="json")

# Create Streaming DataFrames connected to the input Kafka topics

sdf_World_Happiness_Report = app.dataframe(topic=input_topic_World_Happiness_Report)

#Drop Features

sdf_World_Happiness_Report.drop(["overall_rank"])


#Keep Features




#Connect composers with preprocessors 

preprocessor_World_Happiness_Report =((select|scaler)+(selectstr|encoder))



#Pipeline definition 

linearRegPipeline_pipeline = preprocessor_World_Happiness_Report |linearReg
linearRegPipeline_metrics = [mae,mse,r2]


linearRegPipeline = Pipeline(model = linearRegPipeline_pipeline, model_name ='LinearRegression'  , metrics_list = linearRegPipeline_metrics , name = "linearRegPipeline",y="score",output_topic="linearRegPipeline")

hoeffTreePipeline_pipeline = preprocessor_World_Happiness_Report |hoeffTree
hoeffTreePipeline_metrics = [mae,mse,r2]


hoeffTreePipeline = Pipeline(model = hoeffTreePipeline_pipeline, model_name ='HoeffdingAdaptiveTreeRegressor'  , metrics_list = hoeffTreePipeline_metrics , name = "hoeffTreePipeline",y="score",output_topic="hoeffTreePipeline")

knnRegPipeline_pipeline = preprocessor_World_Happiness_Report |knnReg
knnRegPipeline_metrics = [mae,mse,r2]


knnRegPipeline = Pipeline(model = knnRegPipeline_pipeline, model_name ='KNNRegressor'  , metrics_list = knnRegPipeline_metrics , name = "knnRegPipeline",y="score",output_topic="knnRegPipeline")



# Output topics initialization

output_topic_linearRegPipeline = app.topic(linearRegPipeline.output_topic, value_deserializer="json")

output_topic_hoeffTreePipeline = app.topic(hoeffTreePipeline.output_topic, value_deserializer="json")

output_topic_knnRegPipeline = app.topic(knnRegPipeline.output_topic, value_deserializer="json")



#Sdf for each pipeline 
#Train and predict method calls for each pipeline
#If the pipeline has an output topic then we call it 

sdf_linearRegPipeline = sdf_World_Happiness_Report.apply(linearRegPipeline.train_and_predict).to_topic(output_topic_linearRegPipeline)
sdf_hoeffTreePipeline = sdf_World_Happiness_Report.apply(hoeffTreePipeline.train_and_predict).to_topic(output_topic_hoeffTreePipeline)
sdf_knnRegPipeline = sdf_World_Happiness_Report.apply(knnRegPipeline.train_and_predict).to_topic(output_topic_knnRegPipeline)


# ---------- DASHBOARD SETUP ----------

def run_dash():
    dash_app = Dash(__name__)
    
    # Enhanced CSS styling for better appearance
    dash_app.layout = html.Div([
        # Header Section
        html.Div([
            html.Div([
                html.H1("🦫 Beaver ML Pipeline Dashboard", 
                       style={
                           'textAlign': 'center',
                           'color': '#2E86AB',
                           'fontFamily': 'Arial, sans-serif',
                           'fontWeight': 'bold',
                           'margin': '20px 0',
                           'fontSize': '2.5em'
                       }),
                html.P("Real-time monitoring of your streaming ML pipelines",
                      style={
                          'textAlign': 'center',
                          'color': '#666',
                          'fontFamily': 'Arial, sans-serif',
                          'fontSize': '1.2em',
                          'marginBottom': '30px'
                      })
            ])
        ], style={
            'backgroundColor': '#f8f9fa',
            'padding': '20px',
            'borderBottom': '3px solid #2E86AB',
            'marginBottom': '20px'
        }),
        
        # Control Panel
        html.Div([
            html.H3("Dashboard Controls", 
                   style={'color': '#2E86AB', 'fontFamily': 'Arial, sans-serif'}),
            html.Div([
                html.Label("Update Interval (seconds):", 
                          style={'fontWeight': 'bold', 'marginRight': '10px'}),
                dcc.Slider(
                    id='interval-slider',
                    min=1, max=10, step=1, value=2,
                    marks={i: str(i) for i in range(1, 11)},
                    tooltip={"placement": "bottom", "always_visible": True}
                )
            ], style={'marginBottom': '20px'}),
            
            html.Div([
                html.Label("Auto-refresh:", 
                          style={'fontWeight': 'bold', 'marginRight': '10px'}),
                dcc.Checklist(
                    id='auto-refresh-toggle',
                    options=[{'label': ' Enable auto-refresh', 'value': 'auto'}],
                    value=['auto'],
                    style={'display': 'inline-block'}
                )
            ])
        ], style={
            'backgroundColor': '#ffffff',
            'padding': '20px',
            'borderRadius': '10px',
            'boxShadow': '0 2px 10px rgba(0,0,0,0.1)',
            'margin': '0 20px 20px 20px'
        }),
        
        # Pipeline Status Cards
        html.Div([
            html.H3("Pipeline Status", 
                   style={'color': '#2E86AB', 'fontFamily': 'Arial, sans-serif', 'marginBottom': '20px'}),
            html.Div([
                
                html.Div([
                    html.Div([
                        html.H4("linearRegPipeline", 
                               style={'margin': '0', 'color': '#2E86AB'}),
                        html.P("", 
                              style={'margin': '5px 0', 'color': '#666', 'fontSize': '0.9em'}),
                        html.Div(id='status-linearRegPipeline', 
                                children="🟢 Active",
                                style={'fontWeight': 'bold', 'color': '#28a745'})
                    ], style={
                        'backgroundColor': '#ffffff',
                        'padding': '15px',
                        'borderRadius': '8px',
                        'boxShadow': '0 2px 8px rgba(0,0,0,0.1)',
                        'border': '1px solid #e9ecef',
                        'textAlign': 'center'
                    })
                ], style={
                    'width': '31%',
                    'display': 'inline-block',
                    'margin': '0 1%',
                    'verticalAlign': 'top'
                }),
                html.Div([
                    html.Div([
                        html.H4("hoeffTreePipeline", 
                               style={'margin': '0', 'color': '#2E86AB'}),
                        html.P("", 
                              style={'margin': '5px 0', 'color': '#666', 'fontSize': '0.9em'}),
                        html.Div(id='status-hoeffTreePipeline', 
                                children="🟢 Active",
                                style={'fontWeight': 'bold', 'color': '#28a745'})
                    ], style={
                        'backgroundColor': '#ffffff',
                        'padding': '15px',
                        'borderRadius': '8px',
                        'boxShadow': '0 2px 8px rgba(0,0,0,0.1)',
                        'border': '1px solid #e9ecef',
                        'textAlign': 'center'
                    })
                ], style={
                    'width': '31%',
                    'display': 'inline-block',
                    'margin': '0 1%',
                    'verticalAlign': 'top'
                }),
                html.Div([
                    html.Div([
                        html.H4("knnRegPipeline", 
                               style={'margin': '0', 'color': '#2E86AB'}),
                        html.P("", 
                              style={'margin': '5px 0', 'color': '#666', 'fontSize': '0.9em'}),
                        html.Div(id='status-knnRegPipeline', 
                                children="🟢 Active",
                                style={'fontWeight': 'bold', 'color': '#28a745'})
                    ], style={
                        'backgroundColor': '#ffffff',
                        'padding': '15px',
                        'borderRadius': '8px',
                        'boxShadow': '0 2px 8px rgba(0,0,0,0.1)',
                        'border': '1px solid #e9ecef',
                        'textAlign': 'center'
                    })
                ], style={
                    'width': '31%',
                    'display': 'inline-block',
                    'margin': '0 1%',
                    'verticalAlign': 'top'
                })
            ], style={'marginBottom': '30px'})
        ], style={
            'backgroundColor': '#ffffff',
            'padding': '20px',
            'borderRadius': '10px',
            'boxShadow': '0 2px 10px rgba(0,0,0,0.1)',
            'margin': '0 20px 20px 20px'
        }),
        
        # Main Metrics Dashboard
        html.Div([
            html.H3("Live Performance Metrics", 
                   style={'color': '#2E86AB', 'fontFamily': 'Arial, sans-serif', 'marginBottom': '20px'}),
            dcc.Graph(
                id='live-graph',
                style={'height': '600px', 'border': '1px solid #e9ecef', 'borderRadius': '8px'}
            )
        ], style={
            'backgroundColor': '#ffffff',
            'padding': '20px',
            'borderRadius': '10px',
            'boxShadow': '0 2px 10px rgba(0,0,0,0.1)',
            'margin': '0 20px 20px 20px'
        }),
        
        # Individual Pipeline Statistics
        html.Div([
            html.H3("Individual Pipeline Statistics", 
                   style={'color': '#2E86AB', 'fontFamily': 'Arial, sans-serif', 'marginBottom': '20px'}),
            html.Div([
                
                html.Div([
                    html.H4("linearRegPipeline Detailed Stats", 
                           style={'color': '#2E86AB', 'textAlign': 'center', 'marginBottom': '15px'}),
                    dcc.Graph(
                        id='live-stats-linearRegPipeline',
                        style={'height': '400px', 'border': '1px solid #e9ecef', 'borderRadius': '8px'}
                    )
                ], style={
                    'backgroundColor': '#ffffff',
                    'padding': '15px',
                    'borderRadius': '8px',
                    'boxShadow': '0 2px 8px rgba(0,0,0,0.1)',
                    'margin': '10px 0'
                }),
                html.Div([
                    html.H4("hoeffTreePipeline Detailed Stats", 
                           style={'color': '#2E86AB', 'textAlign': 'center', 'marginBottom': '15px'}),
                    dcc.Graph(
                        id='live-stats-hoeffTreePipeline',
                        style={'height': '400px', 'border': '1px solid #e9ecef', 'borderRadius': '8px'}
                    )
                ], style={
                    'backgroundColor': '#ffffff',
                    'padding': '15px',
                    'borderRadius': '8px',
                    'boxShadow': '0 2px 8px rgba(0,0,0,0.1)',
                    'margin': '10px 0'
                }),
                html.Div([
                    html.H4("knnRegPipeline Detailed Stats", 
                           style={'color': '#2E86AB', 'textAlign': 'center', 'marginBottom': '15px'}),
                    dcc.Graph(
                        id='live-stats-knnRegPipeline',
                        style={'height': '400px', 'border': '1px solid #e9ecef', 'borderRadius': '8px'}
                    )
                ], style={
                    'backgroundColor': '#ffffff',
                    'padding': '15px',
                    'borderRadius': '8px',
                    'boxShadow': '0 2px 8px rgba(0,0,0,0.1)',
                    'margin': '10px 0'
                })
            ])
        ], style={
            'backgroundColor': '#ffffff',
            'padding': '20px',
            'borderRadius': '10px',
            'boxShadow': '0 2px 10px rgba(0,0,0,0.1)',
            'margin': '0 20px 20px 20px'
        }),
        
        # Footer
        html.Div([
            html.P("Powered by Beaver DSL 🦫 | Built with Plotly Dash",
                  style={
                      'textAlign': 'center',
                      'color': '#666',
                      'fontFamily': 'Arial, sans-serif',
                      'margin': '0'
                  })
        ], style={
            'backgroundColor': '#f8f9fa',
            'padding': '15px',
            'borderTop': '1px solid #e9ecef',
            'marginTop': '20px'
        }),
        
        # Hidden interval component (controlled by slider)
        dcc.Interval(id='interval', n_intervals=0, interval=2000, disabled=False)
    ], style={
        'backgroundColor': '#f5f5f5',
        'minHeight': '100vh',
        'fontFamily': 'Arial, sans-serif'
    })

    # Callback to update interval based on slider
    @dash_app.callback(
        [Output('interval', 'interval'),
         Output('interval', 'disabled')],
        [Input('interval-slider', 'value'),
         Input('auto-refresh-toggle', 'value')]
    )
    def update_interval(slider_value, auto_refresh):
        interval = slider_value * 1000  # Convert to milliseconds
        disabled = 'auto' not in auto_refresh
        return interval, disabled

    @dash_app.callback(
        Output('live-graph', 'figure'),
        Input('interval', 'n_intervals')
    )
    def update_graph(n):
        fig = make_subplots(
            rows=3, 
            cols=1,
            vertical_spacing=0.08,
            subplot_titles=["linearRegPipeline ()", "hoeffTreePipeline ()", "knnRegPipeline ()"]
        )

        
        linearRegPipeline.add_metrics_traces(fig = fig , row = 1, col = 1 ) 
        
        hoeffTreePipeline.add_metrics_traces(fig = fig , row = 2, col = 1 ) 
        
        knnRegPipeline.add_metrics_traces(fig = fig , row = 3, col = 1 ) 
        

        fig.update_layout(
            height=600,
            title={
                'text': "Live Pipeline Performance Metrics",
                'x': 0.5,
                'xanchor': 'center',
                'font': {'size': 20, 'color': '#2E86AB'}
            },
            margin=dict(t=80, b=40, l=60, r=60),
            showlegend=True,
            plot_bgcolor='rgba(0,0,0,0)',
            paper_bgcolor='rgba(0,0,0,0)',
            font={'family': 'Arial, sans-serif'}
        )
        
        # Update subplot title styling
        fig.update_annotations(font_size=14, font_color='#2E86AB')
        
        return fig

    
    @dash_app.callback(
        Output(
            component_id='live-stats-linearRegPipeline', 
            component_property='figure'
        ), 
        Input(
            component_id='interval', 
            component_property='n_intervals'
        )
    )
    def update_stats_linearRegPipeline(n):
        traces = []  
        layout_updates = linearRegPipeline.add_stats_traces(traces) 
        
        if traces:
            # Merge layout updates with base layout
            base_layout = {
                'title': {
                    
                    'x': 0.5,
                    'xanchor': 'center',
                    'font': {'size': 16, 'color': '#2E86AB'}
                },
                'plot_bgcolor': 'rgba(0,0,0,0)',
                'paper_bgcolor': 'rgba(0,0,0,0)',
                'font': {'family': 'Arial, sans-serif'},
                'margin': dict(t=60, b=40, l=60, r=60)
            }
            
            # Add axis titles and update with layout_updates
            if 'xaxis' not in layout_updates:
                layout_updates['xaxis'] = {}
            if 'yaxis' not in layout_updates:
                layout_updates['yaxis'] = {}
            
            # Only set titles if they don't already exist (don't override pipeline's titles)
            if 'title' not in layout_updates['xaxis']:
                layout_updates['xaxis']['title'] = 'x-axis'
            if 'title' not in layout_updates['yaxis']:
                layout_updates['yaxis']['title'] = 'y-axis'
            
            base_layout.update(layout_updates)
            
            fig = go.Figure(data=traces, layout=go.Layout(**base_layout))
            return fig    
    
        # Return empty figure with message
        return go.Figure().add_annotation(
            x=0.5, y=0.5,
            text="No data available yet...",
            showarrow=False,
            font={'size': 16, 'color': '#666'}
        ).update_layout(
            plot_bgcolor='rgba(0,0,0,0)',
            paper_bgcolor='rgba(0,0,0,0)',
            xaxis={'visible': False},
            yaxis={'visible': False}
        )
    
    
    @dash_app.callback(
        Output(
            component_id='live-stats-hoeffTreePipeline', 
            component_property='figure'
        ), 
        Input(
            component_id='interval', 
            component_property='n_intervals'
        )
    )
    def update_stats_hoeffTreePipeline(n):
        traces = []  
        layout_updates = hoeffTreePipeline.add_stats_traces(traces) 
        
        if traces:
            # Merge layout updates with base layout
            base_layout = {
                'title': {
                    
                    'x': 0.5,
                    'xanchor': 'center',
                    'font': {'size': 16, 'color': '#2E86AB'}
                },
                'plot_bgcolor': 'rgba(0,0,0,0)',
                'paper_bgcolor': 'rgba(0,0,0,0)',
                'font': {'family': 'Arial, sans-serif'},
                'margin': dict(t=60, b=40, l=60, r=60)
            }
            
            # Add axis titles and update with layout_updates
            if 'xaxis' not in layout_updates:
                layout_updates['xaxis'] = {}
            if 'yaxis' not in layout_updates:
                layout_updates['yaxis'] = {}
            
            # Only set titles if they don't already exist (don't override pipeline's titles)
            if 'title' not in layout_updates['xaxis']:
                layout_updates['xaxis']['title'] = 'x-axis'
            if 'title' not in layout_updates['yaxis']:
                layout_updates['yaxis']['title'] = 'y-axis'
            
            base_layout.update(layout_updates)
            
            fig = go.Figure(data=traces, layout=go.Layout(**base_layout))
            return fig    
    
        # Return empty figure with message
        return go.Figure().add_annotation(
            x=0.5, y=0.5,
            text="No data available yet...",
            showarrow=False,
            font={'size': 16, 'color': '#666'}
        ).update_layout(
            plot_bgcolor='rgba(0,0,0,0)',
            paper_bgcolor='rgba(0,0,0,0)',
            xaxis={'visible': False},
            yaxis={'visible': False}
        )
    
    
    @dash_app.callback(
        Output(
            component_id='live-stats-knnRegPipeline', 
            component_property='figure'
        ), 
        Input(
            component_id='interval', 
            component_property='n_intervals'
        )
    )
    def update_stats_knnRegPipeline(n):
        traces = []  
        layout_updates = knnRegPipeline.add_stats_traces(traces) 
        
        if traces:
            # Merge layout updates with base layout
            base_layout = {
                'title': {
                    
                    'x': 0.5,
                    'xanchor': 'center',
                    'font': {'size': 16, 'color': '#2E86AB'}
                },
                'plot_bgcolor': 'rgba(0,0,0,0)',
                'paper_bgcolor': 'rgba(0,0,0,0)',
                'font': {'family': 'Arial, sans-serif'},
                'margin': dict(t=60, b=40, l=60, r=60)
            }
            
            # Add axis titles and update with layout_updates
            if 'xaxis' not in layout_updates:
                layout_updates['xaxis'] = {}
            if 'yaxis' not in layout_updates:
                layout_updates['yaxis'] = {}
            
            # Only set titles if they don't already exist (don't override pipeline's titles)
            if 'title' not in layout_updates['xaxis']:
                layout_updates['xaxis']['title'] = 'x-axis'
            if 'title' not in layout_updates['yaxis']:
                layout_updates['yaxis']['title'] = 'y-axis'
            
            base_layout.update(layout_updates)
            
            fig = go.Figure(data=traces, layout=go.Layout(**base_layout))
            return fig    
    
        # Return empty figure with message
        return go.Figure().add_annotation(
            x=0.5, y=0.5,
            text="No data available yet...",
            showarrow=False,
            font={'size': 16, 'color': '#666'}
        ).update_layout(
            plot_bgcolor='rgba(0,0,0,0)',
            paper_bgcolor='rgba(0,0,0,0)',
            xaxis={'visible': False},
            yaxis={'visible': False}
        )
    
    

    
    @dash_app.callback(
        Output('status-linearRegPipeline', 'children'),
        Input('interval', 'n_intervals')
    )
    def update_status_linearRegPipeline(n):
        # You can add logic here to check actual pipeline status
        # For now, we'll show active status
        return "🟢 Active"
    
    @dash_app.callback(
        Output('status-hoeffTreePipeline', 'children'),
        Input('interval', 'n_intervals')
    )
    def update_status_hoeffTreePipeline(n):
        # You can add logic here to check actual pipeline status
        # For now, we'll show active status
        return "🟢 Active"
    
    @dash_app.callback(
        Output('status-knnRegPipeline', 'children'),
        Input('interval', 'n_intervals')
    )
    def update_status_knnRegPipeline(n):
        # You can add logic here to check actual pipeline status
        # For now, we'll show active status
        return "🟢 Active"
    
    
    dash_app.run(debug=False, use_reloader=False, host='0.0.0.0', port=8050)

if __name__ == '__main__':
    #Run Plotly on different thread
    threading.Thread(target=run_dash, daemon=True).start()
   
    # Run Quix Streams 
    app.run()