# Autogenerated from python.template file

from quixstreams import Application
from quixstreams.models import TopicConfig
from quixstreams.kafka import ConnectionConfig 


from river import preprocessing

from river import optim

from river import metrics

from river import drift
from river import linear_model



optim1 = optim.AdaDelta(
)
preproc1 = preprocessing.AdaptiveStandardScaler(
    lr =1,
    optim =optim1,
    param =0.2,
    test =['model', 'model2'],
    dict ={"true" : 1,"false" : 0,},
    problem =False,
    string ="stringgg",
)
preproc2 = preprocessing.FeatureHasher(
    n_features =10,
    seed =42,
)
testMetric1 = metrics.AdjustedRand(
)
testMetric2 = metrics.CohenKappa(
)
testAlgo = drift.binary.DDM(
)
testAlgo1 = linear_model.ALMAClassifier(
)



connectionConfig = ConnectionConfig( 
    bootstrap_servers = "localhost:39092",
    security_protocol = "sasl_plaintext", 
    sasl_mechanism = "PLAIN",
    sasl_username="username",
    sasl_password="admin_pass",
)

