# Autogenerated from python.template file

from quixstreams import Application
from quixstreams.models import TopicConfig

from river import preprocessing

from river import optim

from river import metrics

from river import drift
from river import linear_model



preproc1 = preprocessing.AdaptiveStandardScaler(
    lr =1,
    optim =logreg,
    param =0.2,
    test =['model', 'model2'],
    dict ={"true" : 1,"false" : 0,},
    problem =False,
)
preproc2 = preprocessing.FeatureHasher(
    lr =1,
)



optim1 = linear_model.logreg(
    lr =1,
)




testMetric1 = linear_model.logreg(
    lr =1,
)
testMetric2 = linear_model.logreg(
    lr =1,
)
