# Autogenerated from python.template file

from quixstreams import Application
from quixstreams.models import TopicConfig
from quixstreams.kafka import ConnectionConfig
from pipeline import *

from river import preprocessing


from river import optim

from river import metrics

from river import linear_model


# Define optimizers
SGD = optim.SGD(
    lr=0.1)


# Define preprocessors
standardScaler = preprocessing.StandardScaler()


# Define metrics
accuracy = metrics.Accuracy()


# Define live data algorithms
log_reg = linear_model.LogisticRegression(
    optimizer=SGD)


# Connection Configuration for quixstreams
connectionConfig = ConnectionConfig(

    bootstrap_servers="localhost:39092",
    security_protocol="plaintext")

# Connection to Kafka
app = Application(
    broker_address=connectionConfig,
    consumer_group="log_reg_cons",
    auto_offset_reset="earliest")

# Input topics

input_topic_phishing = app.topic("Phishing", value_deserializer="json")

# Create Streaming DataFrames connected to the input Kafka topics

sdf_phishing = app.dataframe(topic=input_topic_phishing)


# Define new features


# Connect composers with preprocessors
preprocessor_phishing = standardScaler


# Pipeline definition

linear_algorithm_pipeline = preprocessor_phishing | log_reg

linear_algorithm_metrics = [accuracy]
linear_algorithm = Pipeline(model=linear_algorithm_pipeline, metrics_list=linear_algorithm_metrics,
                            name="linear_algorithm", y="class", output_topic="LogisticRegressionBVR")

# Output topics initialization

output_topic_linear_algorithm = app.topic(
    linear_algorithm.output_topic, value_deserializer="json")


# Sdf for each pipeline
# Train and predict method calls for each pipeline
# If the pipeline has an output topic then we call it

sdf_linear_algorithm = sdf_phishing.apply(
    linear_algorithm.train_and_predict).to_topic(output_topic_linear_algorithm)


# Run Quix Streams
app.run()

# Metric plots for each Pipeline
linear_algorithm.metrics_plot()
