
# Autogenerated using jinja files
from quixstreams import Application
from quixstreams.kafka import ConnectionConfig 
from beaver.pipeline import *
from dash import Dash
from dash.dependencies import Input, Output
from dash import dcc, html
import plotly.graph_objs as go
import threading
from plotly.subplots import make_subplots


from river import tree
from river import ensemble
from river import metrics




hoeff = tree.HoeffdingTreeClassifier(
    split_criterion = 'gini',
    delta = 1e-05,
    grace_period = 2000
)
adaboost = ensemble.AdaBoostClassifier(
    model = hoeff,
    n_models = 5,
    seed = 42
)
logloss = metrics.LogLoss(
)



#Define connection
connectionConfig = ConnectionConfig(
    bootstrap_servers = 'localhost:39092',
    security_protocol = 'plaintext',
)

#Connection to Kafka
app = Application( 
    broker_address = connectionConfig,
    consumer_group = 'ensemble',
    auto_offset_reset = 'earliest',
)

#Input topics 

input_topic_Phishing = app.topic("Phishing", value_deserializer="json")

# Create Streaming DataFrames connected to the input Kafka topics

sdf_Phishing = app.dataframe(topic=input_topic_Phishing)

#Drop Features


#Keep Features




#Connect composers with preprocessors 



#Pipeline definition 

adaboostPipeline_pipeline =adaboost
adaboostPipeline_metrics = [logloss]


adaboostPipeline = Pipeline(model = adaboostPipeline_pipeline, model_name ='AdaBoostClassifier'  , metrics_list = adaboostPipeline_metrics , name = "adaboostPipeline",y="is_phishing",output_topic="adaboostPipeline")



# Output topics initialization

output_topic_adaboostPipeline = app.topic(adaboostPipeline.output_topic, value_deserializer="json")



#Sdf for each pipeline 
#Train and predict method calls for each pipeline
#If the pipeline has an output topic then we call it 

sdf_adaboostPipeline = sdf_Phishing.apply(adaboostPipeline.train_and_predict).to_topic(output_topic_adaboostPipeline)


# ---------- DASHBOARD SETUP ----------

def run_dash():
    dash_app = Dash(__name__)
    dash_app.layout = html.Div([
         html.H2("Pipelines' Plots" , style={
        'textAlign': 'center',  # Center the text

        'fontFamily': 'sans-serif',  # Change the font family
        'font-weight': 'normal',  # Make the text bold
        }),
        dcc.Interval(id='interval', n_intervals=0),
        dcc.Graph(id='live-graph'), 
        html.Div(
            children=[
                
                dcc.Graph(
                    id='live-stats-adaboostPipeline',
                    #style={'margin': 'auto', 'display': 'block', 'width':'70%'}
                )
            ]
        )
    ])

    @dash_app.callback(
        Output('live-graph', 'figure'),
        Input('interval', 'n_intervals')
    )
    def update_graph(n):
        fig = make_subplots(rows=1, cols=1 , vertical_spacing=0.1)

        
        adaboostPipeline.add_metrics_traces(fig = fig , row = 1, col = 1 ) 
        

        fig.update_layout(height=600, title="Live Metrics", margin=dict(t=40, b=40), showlegend=True )
        return fig


    
    @dash_app.callback(
        Output(
            component_id='live-stats-adaboostPipeline', 
            component_property='figure'
        ), 
        Input(
            component_id='interval', 
            component_property='n_intervals'
        )
    )

      
    def update_stats_adaboostPipeline(n):
        
        traces = []  
        
        adaboostPipeline.add_stats_traces(traces) 
              

        
        if traces:
            fig = go.Figure(
                    data=traces, 
                    layout= go.Layout(
                        title='adaboostPipeline Statistics'
                    )
            )
            return fig    
    
        return go.Figure()
    
    dash_app.run(debug=False, use_reloader=False)

if __name__ == '__main__':
    #Run Plotly on different thread
    threading.Thread(target=run_dash, daemon=True).start()
   
    # Run Quix Streams 
    app.run()