
# Autogenerated using jinja files
from quixstreams import Application
from quixstreams.kafka import ConnectionConfig 
from beaver.pipeline import *
from dash import Dash
from dash.dependencies import Input, Output
from dash import dcc, html
import plotly.graph_objs as go
import threading
from plotly.subplots import make_subplots


from river import optim
from river import linear_model
from river import preprocessing
from river import metrics
from river import bandit
from river import model_selection




sgd1 = optim.SGD(
    lr = 0.0001
)
sgd2 = optim.SGD(
    lr = 1e-05
)
log1 = linear_model.LogisticRegression(
    optimizer = sgd1
)
log2 = linear_model.LogisticRegression(
    optimizer = sgd2
)
scaler = preprocessing.StandardScaler(
)
acc = metrics.Accuracy(
)
epsilon = bandit.EpsilonGreedy(
    epsilon = 0.1,
    decay = 0.001,
    burn_in = 20,
    seed = 42
)
bandit = model_selection.BanditClassifier(
    models = [log1,log2],
    metric = acc,
    policy = epsilon
)



#Define connection
connectionConfig = ConnectionConfig(
    bootstrap_servers = 'localhost:39092',
    security_protocol = 'plaintext',
)

#Connection to Kafka
app = Application( 
    broker_address = connectionConfig,
    consumer_group = 'model_selection_models',
    auto_offset_reset = 'earliest',
)

#Input topics 

input_topic_Phishing = app.topic("Phishing", value_deserializer="json")

# Create Streaming DataFrames connected to the input Kafka topics

sdf_Phishing = app.dataframe(topic=input_topic_Phishing)

#Drop Features


#Keep Features




#Connect composers with preprocessors 

preprocessor_Phishing =scaler



#Pipeline definition 

banditPipeline_pipeline = preprocessor_Phishing |bandit
banditPipeline_metrics = [acc]


banditPipeline = Pipeline(model = banditPipeline_pipeline, model_name ='BanditClassifier'  , metrics_list = banditPipeline_metrics , name = "banditPipeline",y="is_phishing",output_topic="banditPipeline")



# Output topics initialization

output_topic_banditPipeline = app.topic(banditPipeline.output_topic, value_deserializer="json")



#Sdf for each pipeline 
#Train and predict method calls for each pipeline
#If the pipeline has an output topic then we call it 

sdf_banditPipeline = sdf_Phishing.apply(banditPipeline.train_and_predict).to_topic(output_topic_banditPipeline)


# ---------- DASHBOARD SETUP ----------

def run_dash():
    dash_app = Dash(__name__)
    dash_app.layout = html.Div([
         html.H2("Pipelines' Plots" , style={
        'textAlign': 'center',  # Center the text

        'fontFamily': 'sans-serif',  # Change the font family
        'font-weight': 'normal',  # Make the text bold
        }),
        dcc.Interval(id='interval', n_intervals=0),
        dcc.Graph(id='live-graph'), 
        html.Div(
            children=[
                
                dcc.Graph(
                    id='live-stats-banditPipeline',
                    #style={'margin': 'auto', 'display': 'block', 'width':'70%'}
                )
            ]
        )
    ])

    @dash_app.callback(
        Output('live-graph', 'figure'),
        Input('interval', 'n_intervals')
    )
    def update_graph(n):
        fig = make_subplots(rows=1, cols=1 , vertical_spacing=0.1)

        
        banditPipeline.add_metrics_traces(fig = fig , row = 1, col = 1 ) 
        

        fig.update_layout(height=600, title="Live Metrics", margin=dict(t=40, b=40), showlegend=True )
        return fig


    
    @dash_app.callback(
        Output(
            component_id='live-stats-banditPipeline', 
            component_property='figure'
        ), 
        Input(
            component_id='interval', 
            component_property='n_intervals'
        )
    )

      
    def update_stats_banditPipeline(n):
        
        traces = []  
        
        banditPipeline.add_stats_traces(traces) 
              

        
        if traces:
            fig = go.Figure(
                    data=traces, 
                    layout= go.Layout(
                        title='banditPipeline Statistics'
                    )
            )
            return fig    
    
        return go.Figure()
    
    dash_app.run(debug=False, use_reloader=False)

if __name__ == '__main__':
    #Run Plotly on different thread
    threading.Thread(target=run_dash, daemon=True).start()
   
    # Run Quix Streams 
    app.run()